# Generated by Django 4.2.5 on 2024-05-21 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_timestamp_profile_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
