# Generated by Django 4.2.5 on 2024-06-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_remove_userprofile_following_userprofile_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
    ]
